spring.application.name=ecommerce-backend
server.port=8090

spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata';
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.auto-commit=true

spring.session.store-type=none

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.num-ctx=8192

logging.level.org.springframework.ai=INFO
spring.jpa.hibernate.ddl-auto=validate
